#uby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
      

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y libldap-2dev build-essential
      - run: ruby extconf.rb --with-openldap2
      - run: sudo apt-get install libsasl2-dev
      - run: make clean
      - run: make
      - run: sudo make install
      - run: gem build ruby-ldap.gemspec
      - run: sudo gem install ruby-ldap-0.9.19.gem